### ISSUE TITLE
Boot failure on AM43xx

### ISSUE THREAD

**Issue by glneo** [OP-TEE/optee_os#1536]
Hello all,

On AM43xx the current master fails to boot with:
```
DEBUG:   [0x7500faa8] TEE-CORE:add_phys_mem:325: CFG_SHMEM_START type NSEC_SHM 0xbf700000 size 0x00400000
DEBUG:   [0x7500faa8] TEE-CORE:add_phys_mem:325: CFG_TA_RAM_START type TA_RAM 0xbdc00000 size 0x01b00000
DEBUG:   [0x7500faa8] TEE-CORE:add_phys_mem:325: CFG_TEE_RAM_START type TEE_RAM 0xbdb00000 size 0x00100000
DEBUG:   [0x7500faa8] TEE-CORE:add_phys_mem:325: ROUNDDOWN(SECRAM_BASE, CORE_MMU_DEVICE_SIZE) type IO_SEC 0x40200000 size 0x00100000
DEBUG:   [0x7500faa8] TEE-CORE:add_phys_mem:325: CONSOLE_UART_BASE type IO_NSEC 0x44e00000 size 0x00100000
DEBUG:   [0x7500faa8] TEE-CORE:add_phys_mem:325: GICD_BASE type IO_SEC 0x48200000 size 0x00100000
DEBUG:   [0x7500faa8] TEE-CORE:add_phys_mem:325: GICC_BASE type IO_SEC 0x48200000 size 0x00100000
DEBUG:   [0x7500faa8] TEE-CORE:add_phys_mem:338: Physical mem map overlaps 0x48200000
DEBUG:   [0x7500faa8] TEE-CORE:add_phys_mem:325: SECRAM_BASE type IO_SEC 0x40200000 size 0x00200000
DEBUG:   [0x7500faa8] TEE-CORE:add_phys_mem:338: Physical mem map overlaps 0x40200000
DEBUG:   [0x7500faa8] TEE-CORE:add_phys_mem:325: PL310_BASE type IO_SEC 0x48200000 size 0x00100000
DEBUG:   [0x7500faa8] TEE-CORE:add_phys_mem:338: Physical mem map overlaps 0x48200000
DEBUG:   [0x7500faa8] TEE-CORE:add_phys_mem:325: RNG_BASE type IO_SEC 0x48300000 size 0x00100000
DEBUG:   [0x7500faa8] TEE-CORE:add_va_space:364: type RES_VASPACE size 0x00a00000
DEBUG:   [0x7500faa8] TEE-CORE:add_va_space:364: type (null) size 0x00a00000
DEBUG:   [0x7500faa8] TEE-CORE:dump_mmap_table:478: type RES_VASPACE  va 0xba300000..0xbacfffff pa 0x00000000..0x009fffff size 0x00a00000 (pgdir)
DEBUG:   [0x7500faa8] TEE-CORE:dump_mmap_table:478: type IO_SEC       va 0xbad00000..0xbadfffff pa 0x48300000..0x483fffff size 0x00100000 (pgdir)
DEBUG:   [0x7500faa8] TEE-CORE:dump_mmap_table:478: type IO_SEC       va 0xbae00000..0xbaefffff pa 0x48200000..0x482fffff size 0x00100000 (pgdir)
DEBUG:   [0x7500faa8] TEE-CORE:dump_mmap_table:478: type IO_SEC       va 0xbaf00000..0xbb0fffff pa 0x40200000..0x403fffff size 0x00200000 (pgdir)
DEBUG:   [0x7500faa8] TEE-CORE:dump_mmap_table:478: type IO_NSEC      va 0xbb100000..0xbb1fffff pa 0x44e00000..0x44efffff size 0x00100000 (pgdir)
DEBUG:   [0x7500faa8] TEE-CORE:dump_mmap_table:478: type NSEC_SHM     va 0xbb200000..0xbb5fffff pa 0xbf700000..0xbfafffff size 0x00400000 (pgdir)
DEBUG:   [0x7500faa8] TEE-CORE:dump_mmap_table:478: type TA_RAM       va 0xbb600000..0xbd0fffff pa 0xbdc00000..0xbf6fffff size 0x01b00000 (pgdir)
DEBUG:   [0x7500faa8] TEE-CORE:dump_mmap_table:478: type (null)       va 0xbd100000..0xbdafffff pa 0x00000000..0x009fffff size 0x00a00000 (pgdir)
DEBUG:   [0x7500faa8] TEE-CORE:dump_mmap_table:478: type TEE_RAM      va 0xbdb00000..0xbdbfffff pa 0xbdb00000..0xbdbfffff size 0x00100000 (pgdir)
```

Bisecting shows c6c6979 ("mm: add new VA region for dynamic shared buffers") as the culprit, same as in https://github.com/OP-TEE/optee_os/issues/1511, in fact even the boot log looks similar. This may even be the problem in https://github.com/OP-TEE/optee_os/issues/1535.

Reverting this patch fixes this issue for me, maybe we should just revert this until it is better understood why it is breaking so many boards.

**Comment by dnovick** [comment]
Sorry for the stupid question, as I'm not a git guru yet. How does one revert a particular patch? It looks like maybe "git-revert"?

Dave

**Comment by jforissier** [comment]
@glneo I'm puzzled, the log you're showing can't be latest master, because it says 'type (null)' and that missing description string was fixed several days ago. And later the hang was fixed by https://github.com/OP-TEE/optee_os/issues/1517.
So can you please make sure you're up to date ?

@dnovick yes, you revert a commit with `git revert <commit-sha1>`.

**Comment by glneo** [comment]
@jforissier Sorry, copy/paste error, that was the log after the bisect, here is the latest log from master:
```
DEBUG:   [0x19021004] TEE-CORE:add_phys_mem:318: CFG_SHMEM_START type NSEC_SHM 0xbf700000 size 0x00400000
DEBUG:   [0x19021004] TEE-CORE:add_phys_mem:318: CFG_TA_RAM_START type TA_RAM 0xbdc00000 size 0x01b00000
DEBUG:   [0x19021004] TEE-CORE:add_phys_mem:318: CFG_TEE_RAM_START type TEE_RAM 0xbdb00000 size 0x00100000
DEBUG:   [0x19021004] TEE-CORE:add_phys_mem:318: CONSOLE_UART_BASE type IO_NSEC 0x44e00000 size 0x00100000
DEBUG:   [0x19021004] TEE-CORE:add_phys_mem:318: GICD_BASE type IO_SEC 0x48200000 size 0x00100000
DEBUG:   [0x19021004] TEE-CORE:add_phys_mem:318: GICC_BASE type IO_SEC 0x48200000 size 0x00100000
DEBUG:   [0x19021004] TEE-CORE:add_phys_mem:331: Physical mem map overlaps 0x48200000
DEBUG:   [0x19021004] TEE-CORE:add_phys_mem:318: SECRAM_BASE type IO_SEC 0x40200000 size 0x00200000
DEBUG:   [0x19021004] TEE-CORE:add_phys_mem:318: TZDRAM_BASE type RAM_SEC 0xbdb00000 size 0x00100000
DEBUG:   [0x19021004] TEE-CORE:add_phys_mem:318: PL310_BASE type IO_SEC 0x48200000 size 0x00100000
DEBUG:   [0x19021004] TEE-CORE:add_phys_mem:331: Physical mem map overlaps 0x48200000
DEBUG:   [0x19021004] TEE-CORE:add_phys_mem:318: RNG_BASE type IO_SEC 0x48300000 size 0x00100000
DEBUG:   [0x19021004] TEE-CORE:add_va_space:357: type RES_VASPACE size 0x00a00000
DEBUG:   [0x19021004] TEE-CORE:add_va_space:357: type SHM_VASPACE size 0x00a00000
DEBUG:   [0x19021004] TEE-CORE:dump_mmap_table:471: type RES_VASPACE  va 0xba200000..0xbabfffff pa 0x00000000..0x009fffff size 0x00a00000 (pgdir)
DEBUG:   [0x19021004] TEE-CORE:dump_mmap_table:471: type IO_SEC       va 0xbac00000..0xbacfffff pa 0x48300000..0x483fffff size 0x00100000 (pgdir)
DEBUG:   [0x19021004] TEE-CORE:dump_mmap_table:471: type IO_SEC       va 0xbad00000..0xbadfffff pa 0x48200000..0x482fffff size 0x00100000 (pgdir)
DEBUG:   [0x19021004] TEE-CORE:dump_mmap_table:471: type IO_SEC       va 0xbae00000..0xbaffffff pa 0x40200000..0x403fffff size 0x00200000 (pgdir)
DEBUG:   [0x19021004] TEE-CORE:dump_mmap_table:471: type IO_NSEC      va 0xbb000000..0xbb0fffff pa 0x44e00000..0x44efffff size 0x00100000 (pgdir)
DEBUG:   [0x19021004] TEE-CORE:dump_mmap_table:471: type RAM_SEC      va 0xbb100000..0xbb1fffff pa 0xbdb00000..0xbdbfffff size 0x00100000 (pgdir)
DEBUG:   [0x19021004] TEE-CORE:dump_mmap_table:471: type NSEC_SHM     va 0xbb200000..0xbb5fffff pa 0xbf700000..0xbfafffff size 0x00400000 (pgdir)
DEBUG:   [0x19021004] TEE-CORE:dump_mmap_table:471: type TA_RAM       va 0xbb600000..0xbd0fffff pa 0xbdc00000..0xbf6fffff size 0x01b00000 (pgdir)
DEBUG:   [0x19021004] TEE-CORE:dump_mmap_table:471: type SHM_VASPACE  va 0xbd100000..0xbdafffff pa 0x00000000..0x009fffff size 0x00a00000 (pgdir)
DEBUG:   [0x19021004] TEE-CORE:dump_mmap_table:471: type TEE_RAM      va 0xbdb00000..0xbdbfffff pa 0xbdb00000..0xbdbfffff size 0x00100000 (pgdir)
```

We still hang at this point, https://github.com/OP-TEE/optee_os/pull/1517 does not fix the issue for me. Commenting out the following line fixes the issue for me:
```
if (!core_mmu_is_dynamic_vaspace(mm))
```
in core_mmu_v7.c

So why do we skip dynamic area mapping? The fix you made seems to miss some underling issue here involving these memory areas.

**Comment by jforissier** [comment]
https://github.com/OP-TEE/optee_os/pull/1517 changes LPAE only, and you're using v7 (non-LPAE).
To be honest I don't quite understand the purpose of these "dynamic" mappings, and they're not useable yet they are just preparing for later commits so if I don't get a proper fix rapidly I'll just revert the culprit.

**Comment by jforissier** [comment]
@glneo I suppose you were notified when Etienne created PR 1537, in any case: can you check and give your Tested-by if that works for you? Thanks.

**Comment by glneo** [comment]
Fixed by: https://github.com/OP-TEE/optee_os/pull/1537
