### ISSUE TITLE
File 'gen_rootfs/busybox/****/simple.script' could not be opened for reading when 'make all' for Hikey Board.

### ISSUE THREAD

**Issue by targetnull** [OP-TEE/optee_os#542]
Hi, I came across another error as follows and I really wish to get help from you.

I have run `repo sync` to get the Hikey branch of the project and I am sure I get the whole project(The average download speed is over 1M/s so it definitely has **nothing** to do with a broken project)

The problem occured when I run `sudo make all`.It worked fine at the beginning. However, it didn't last too long. Here is the error **when generating boot-img**
>File /home/targetnull/devel/optee_hikey/build/../gen_rootfs/busybox/examples/udhcp/simple.script could not be opened for reading
 line 474
sudo -p "[sudo] Password:" true
if [ -d .tmpbootimg ] ; then sudo rm -rf .tmpbootimg ; fi
mkdir -p .tmpbootimg
dd if=/dev/zero of=/home/targetnull/devel/optee_hikey/build/../out/boot-fat.uefi.img bs=512 count=131072 status=none
dd: invalid status flag: `none'
Try `dd --help' for more information.
make: *** [boot-img] Error 1

But it confuses me that **there does exist the file, but not under gen_rootfs directory**, it is under `busybox/****/simple.script` **without** the preffix **gen_rootfs/**. So what might be the reason?
Is it normal? Did I miss any libs or tools or configurations?

Really need your help.
Thanks in advance.
Tgn

**Comment by targetnull** [comment]
Has anyone run into the same error?

**Comment by vchong** [comment]
Looks like a bug. Thanks for reporting! We'll update the build script asap, but in the meantime, you can apply the fix below manually.

In hikey.mk line 254 (https://github.com/OP-TEE/build/blob/master/hikey.mk#L254), replace GEN_ROOTFS_PATH with ROOT.

**Comment by targetnull** [comment]
@vchong 
Thanks for fixing it, but I have fixed it myself by creating a soft link `./genrootfs/busybox -> ../busybox`.

Unluckily, I came across another error later on, and I think it has something to do with `dd in coreutils`, the error is very similar to the one in this issue:
>dd: invalid status flag: `(I forget the flag....)`
>Try `dd --help' for more information.
>make: *** [boot-img] Error 1

I forget what the flag is, but I remember it's also in the process when making **[boot-img]**.
I did some google work, and found out the reason might be that I had a low version `dd(coreutils)`.

So I updated `coreutils` to the latest stable version, which is **8.24**, but the error remains.

BTW, I'm using Ubuntu12.04.5(32-bit) in VMWare, does this has something to do with it? Or just another bug?

**Comment by vchong** [comment]
This does not look like a bug.

You had below error when making boot-img:
```dd: invalid status flag: none' Trydd --help' for more information.```
Is this the flag you forgot? If so, yes, that seems to indicate you have an old version of dd. Are you sure you updated coreutils properly? Check the version of your dd and make sure it's higher than 8.20 using command ```dd --version```.

Or try replacing ```status=none``` in the dd command with ```2> /dev/null```.

**Comment by targetnull** [comment]
1. You're right, there is something wrong with my coreutils. I reinstalled it and the error didn't show up agian. And the version is indeed 8.24.
2. Unluckily......... again. I came across the error below

>sudo mkfs.fat -n "BOOT IMG" /home/targetnull/devel/optee_hikey/build/../out/boot-fat.uefi.img >/dev/null
sudo: mkfs.fat: command not found
make: *** [boot-img] Error 1

I only find **mkfs.vfat** instead of **mkfa.fat**, so I replaced it with `mkfa.vfat`, but another error just showd up!
>python gen_loader.py -o ptable.img --img_prm_ptable=prm_ptable.img --img_sec_ptable=sec_ptable.img
+-----------------------------------------------------------+
 Input Images:
     primary partition table:       prm_ptable.img
     secondary partition table:     sec_ptable.img
 Ouput Image:                       ptable.img
+-----------------------------------------------------------+
It's not partition table image.
make[1]: *** [ptable.img] Error 4
make[1]: Leaving directory `/home/targetnull/devel/optee_hikey/l-loader'
make: *** [lloader] Error 2

Could you please tell me what environment you are using to develop OP-TEE? CentOS6.5 , Ubuntu14.04.3 or something else? And 32-bit or 64-bit? it seems that I always meet strange errors and I've spent several days on it. That almost drives me crazy!

One of my classmate told me lastnight that he had run `make all` successfully in Ubuntu 14.04.1, though Hikey was not able to boot normally.

**Comment by jbech-linaro** [comment]
@targetnull most of us are using Ubuntu based systems. I know some uses Ubuntu 12.04, 14.04 and 15.04 and then a couple of us has been using Linux Mint 16, 17.1 and 17.2. In practice we're all using 64-bit versions also. Me myself are using Mint 17.1 for the moment and I have both QEMU, FVP, Juno, Hikey and the MediaTek board working.

By the way, can I close this issue, since the original issue has been solved and merged?

**Comment by targetnull** [comment]
@jbech-linaro OK, I will open an new issue.
Thanks for your help and vchong.

**Comment by jbech-optee-adm** [comment]
Thanks @targetnull , I'm closing this issue.
